### ISSUE TITLE
Allow mods to ban users without using Nino

### ISSUE THREAD

**Issue by ohlookitsderpy** [auguwu/Nino#140]
For example:

I ban a user using Discord. The bot should listen for this and create a case in the mod-log, then allowing the moderator to set a reason.

This could apply to mute/unmute, ban and kick.

**Comment by auguwu** [comment]
So like, using the `Ban User` in the Context Menu on Discord? Seems like an easy for for bans but unknown for kicks/mutes/unmutes, will let @dondish find that out for kicks/mutes/unmutes

**Comment by ohlookitsderpy** [comment]
yee

**Comment by auguwu** [comment]
It's easy for ban members since Discord provides a `guildBanAdd`/`guildBanRemove` event that we can emit and do the process, for kicks/mutes/unmutes, will let dondish handle that

**Comment by ohlookitsderpy** [comment]
@dondish get to work

**Comment by auguwu** [comment]
Implemented into the cutting edge build
