### ISSUE TITLE
Let only the moderator edit the reason

### ISSUE THREAD

**Issue by auguwu** [auguwu/Nino#144]
Title is self explaintory

**Comment by ohlookitsderpy** [comment]
why? i think that if a mod does something and goes offline, then someone has an updated copy they should be able to publish

**Comment by ohlookitsderpy** [comment]
honestly, if mods abuse shit it's the admin's fault for hiring them

**Comment by dondish** [comment]
I am against this. It is just a bad idea.

**Comment by ohlookitsderpy** [comment]
close it

**Comment by auguwu** [comment]
fuck you both /s
