### ISSUE TITLE
[Feature Request] Show previous message on message update

### ISSUE THREAD

**Issue by ohlookitsderpy** [auguwu/Nino#278]

**Comment by dondish** [comment]
That's quite problematic, as you know Discord does not give you the information, and it requires saving a message cache which can be borderline user data.
This can also take an immense amount of space.

**Comment by auguwu** [comment]
Why save the message data? Doesn't Eris provide the old message and the new message content when the event is emitted?

**Comment by auguwu** [comment]
It does, you can't grab the old data if the old message is `null` (aka it wasn't cached)

https://abal.moe/Eris/docs/Client#event-messageUpdate

**Comment by dondish** [comment]
The cache resets on each restart though

**Comment by auguwu** [comment]
I implemented the fix

![example](https://i.augu.dev/uploads/d72a3aac39da3460.png)
