### ISSUE TITLE
Automod invites bypass

### ISSUE THREAD

**Issue by dvhe** [auguwu/Nino#58]
If you send a message and then edit your message with an invite, you can bypass the automod. As seen here [https://quak.ovh/2bf3Dz5.gif](url)

**Comment by auguwu** [comment]
Me and don will figure out a fix. Thanks Kyle!

**Comment by dondish** [comment]
This will be easy to implement. Will be done in the next build.

**Comment by dondish** [comment]
Done a few builds ago
